server.port=${PORT:8089}
spring.application.name=notification-service

# Database (AWS RDS Production) 🛰️
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://caresync-db.cduc4o4kscep.ap-southeast-2.rds.amazonaws.com:3306/caresync_notification?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:arpit123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate 🦾
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Security (JWT)
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=86400000
