services:
  db:
    image: mysql:8.0
    container_name: caresync-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medibook_auth
    ports:
      - "3307:3306"
