server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 🛡️ Auth Service (Identity & Login)
        - id: auth-service
          uri: https://auth-service-lm7j.onrender.com
          predicates:
            - Path=/api/auth/**

        # 🩺 Provider Service (Profiles & Vetting)
        - id: provider-service
          uri: https://provider-service-bgxb.onrender.com
          predicates:
            - Path=/api/providers/**, /api/admin/**
