server.port=${PORT:8083}
spring.application.name=patient-service

# Database (AWS RDS Production) 🛰️
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://caresync-db.cduc4o4kscep.ap-southeast-2.rds.amazonaws.com:3306/caresync_patient?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:arpit123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate 🦾
spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Security (JWT) - MUST MATCH OTHER SERVICES
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=86400000

# Inter-service URLs
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
